name: post

on:
    schedule:
        - cron: "0 0 */3 * *"

jobs:
    post:
        runs-on: ubuntu-latest
    
        steps:
            - uses: actions/checkout@v4
                
            - name: substitute twitter consumer key
              uses: jossef/action-set-json-field@v2.1
              with:
                file: bot/twitter/appsettings.json
                field: Twitter.ConsumerKey
                value: ${{ secrets.TWITTER_CONSUMERKEY }}
        
            - name: substitute consumer secret
              uses: jossef/action-set-json-field@v2.1
              with:
                file: bot/twitter/appsettings.json
                field: Twitter.ConsumerSecret
                value: ${{ secrets.TWITTER_CONSUMERSECRET }}
        
            - name: substitute twitter access token
              uses: jossef/action-set-json-field@v2.1
              with:
                file: bot/twitter/appsettings.json
                field: Twitter.AccessToken
                value: ${{ secrets.TWITTER_ACCESSTOKEN }}
        
            - name: substitute twitter access token secret
              uses: jossef/action-set-json-field@v2.1
              with:
                file: bot/twitter/appsettings.json
                field: Twitter.AccessTokenSecret
                value: ${{ secrets.TWITTER_ACCESSTOKENSECRET }}
        
            - name: substitute base deputy file paths
              uses: jossef/action-set-json-field@v2.1
              with:
                file: bot/twitter/appsettings.json
                field: FilesPaths.BaseDeputyFilePath
                value: ${{ github.workspace }}/bot/twitter/deputies.json
        
            - name: substitute base old deputy file paths
              uses: jossef/action-set-json-field@v2.1
              with:
                file: bot/twitter/appsettings.json
                field: FilesPaths.OldDeputyFilePath
                value: ${{ github.workspace }}/bot/twitter/old_deputies.json
        
            - name: substitute picture file path
              uses: jossef/action-set-json-field@v2.1
              with:
                file: bot/twitter/appsettings.json
                field: FilesPaths.PictureFilePath
                value: ${{ github.workspace }}/datas/pictures/
        
            - name: setup .NET
              uses: actions/setup-dotnet@v4
              with:
                dotnet-version: 8.0.x

            - name: clear nuget cache
              run: dotnet nuget locals all --clear
            
            - name: clean
              run: dotnet clean bot/twitter/Jaieteelu.sln

            - name: restore
              run: dotnet restore bot/twitter/
            
            - name: build
              run: dotnet build --no-restore -c Release bot/twitter/Jaieteelu.sln